name: update_resource_list

on:
  schedule:
    - cron: '0 0 * * *'     # Every day at midnight 
    
  workflow_dispatch:        # Manual invocation
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install pandas
          #pip install requests
          #pip install beautifulsoup4
          #pip install lxml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script # run file
        run: |
          python extract_resources.py

      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Andy Stewart'
          git config --global user.email 'andy.stewart@live.com'
          git commit -am "Automated commit"
          git push
      
